name: dagger
on:
  push:
    branches: [feature/dagger-for-cicd-pipelines]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          verb: call
          module: github.com/shykes/daggerverse/hello@v0.1.2
          args: hello --greeting="hey there!"