name: Terraform Orchestration

on: 
  workflow_dispatch:
  push:
    branches:
      - "feature/terraform-github-action"

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:

      - name: Terraform Init
        working-directory: ./docs/terraform
        shell: bash
        run: terraform init

      - name: Terraform Plan
        working-directory: ./docs/terraform
        shell: bash
        run: terraform plan

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    steps:
  
      - name: Terraform Init
        working-directory: ./docs/terraform
        shell: bash
        run: terraform init
  
      - name: Terraform Apply
        working-directory: ./docs/terraform
        shell: bash
        run: terraform apply